model: meta-llama/Llama-2-13b-chat-hf
train_prompts:
- prompts/continent-countries
test_prompts:
- prompts/continent-countries
alg_config:
  n_iters: 50
output_dir: results-lora/llama-2-13b-chat/leave-one-in/continent-countries
