model: Qwen/Qwen2.5-7B-Instruct
train_prompts: []
test_prompts:
 - src/trout/eval/diffuseDistributions/prompts/baby-names
alg_config:
  n_iters: 50
  early_stop: true
output_dir: results-lora/Qwen2.5-7B-Instruct/baby-names
