model: google/gemma-7b-it
train_prompts:
- prompts/baby-names
test_prompts:
- prompts/baby-names
alg_config:
  n_iters: 50
  early_stop: true
output_dir: results-lora/gemma-7b-it/leave-one-in/baby-names
