model: google/gemma-7b-it
train_prompts:
- prompts/continent-countries
test_prompts:
- prompts/continent-countries
alg_config:
  n_iters: 50
output_dir: results-lora/gemma-7b-it/leave-one-in/continent-countries
