model: google/gemma-7b-it
train_prompts:
- prompts/baby-names
- prompts/day-date
- prompts/fruits
- prompts/numbers
- prompts/occupations
test_prompts:
- prompts/continent-countries
alg_config:
  n_iters: 50
output_dir: results-lora/gemma-7b-it/leave-one-out/continent-countries
