model: meta-llama/Llama-2-13b-chat-hf
train_prompts:
- prompts/occupations
test_prompts:
- prompts/occupations
alg_config:
  n_iters: 50
  early_stop: true
output_dir: results-lora/llama-2-13b-chat/leave-one-in/occupations
